package Presentation.Controllers;

import Business.Entities.ParkingSpace;
import Business.Entities.VehicleType;
import Business.Services.AdminService;
import Business.Services.ParkingService;
import Presentation.Views.AdminParkingManagementView;

import javax.swing.SwingWorker;
import javax.swing.SwingUtilities;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ExecutionException;

/**
 * Controller for the admin parking space management view.
 * Handles creating, editing, deleting, and loading parking spaces.
 */
public class AdminController {
    private AdminParkingManagementView adminView;
    private ParkingService parkingService;
    private AdminService adminService;
    private volatile int spacesLoadId;

    /**
     * Constructs the controller and wires it to the given view.
     *
     * @param adminView      the admin parking management view
     * @param parkingService the parking service
     */
    public AdminController(AdminParkingManagementView adminView, ParkingService parkingService) {
        this.adminView = adminView;
        this.parkingService = parkingService;
        adminView.setController(this);
    }

    /** Sets the admin service used for reservation operations. */
    public void setAdminService(AdminService adminService) {
        this.adminService = adminService;
    }

    /** Clears the table, loads all spaces, and makes the view visible. */
    public void showView() {
        adminView.clearSpacesTable();
        loadSpaces();
        adminView.setVisible(true);
    }

    /**
     * Reloads the view if it is currently visible.
     * Safe to call from any thread.
     */
    public void refreshIfVisible() {
        if (adminView == null || !adminView.isVisible())
            return;

        if (SwingUtilities.isEventDispatchThread()) {
            loadSpaces();
        } else {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    loadSpaces();
                }
            });
        }
    }

    /**
     * Creates a new parking space on the given floor with the given vehicle type.
     * The space code is auto-generated by the service.
     *
     * @param floor the floor number
     * @param type  the vehicle type for the space
     */
    public void createSpace(int floor, VehicleType type) {
        adminView.setLoading(true);
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                ParkingSpace space = new ParkingSpace(null, floor, type, false, false, null, null);
                parkingService.createParkingSpace(space);
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    loadSpaces();
                } catch (InterruptedException | ExecutionException e) {
                    adminView.setLoading(false);
                    Throwable cause = e.getCause();
                    adminView.showError(cause != null ? cause.getMessage() : "Failed to create space.");
                }
            }
        }.execute();
    }

    /**
     * Updates the floor and vehicle type of an existing parking space.
     *
     * @param code  the space code to edit
     * @param floor the new floor number
     * @param type  the new vehicle type
     */
    public void editSpace(String code, int floor, VehicleType type) {
        adminView.setLoading(true);
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                ParkingSpace space = parkingService.findByCode(code);
                if (space == null) {
                    throw new IllegalArgumentException("Space not found: " + code);
                }
                space.setFloor(floor);
                space.setVehicleType(type);
                parkingService.updateParkingSpaceDetails(space);
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    loadSpaces();
                } catch (InterruptedException | ExecutionException e) {
                    adminView.setLoading(false);
                    Throwable cause = e.getCause();
                    adminView.showError(cause != null ? cause.getMessage() : "Failed to edit space.");
                }
            }
        }.execute();
    }

    /**
     * Deletes a parking space by code.
     * Occupied spaces cannot be deleted.
     * Any active reservation is reassigned or cancelled before deletion.
     *
     * @param code the space code to delete
     */
    public void deleteSpace(String code) {
        adminView.setLoading(true);
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                ParkingSpace space = parkingService.findByCode(code);
                if (space == null) {
                    throw new IllegalArgumentException("Space not found: " + code);
                }
                if (space.isOccupied()) {
                    throw new IllegalStateException("Cannot delete space \"" + code + "\": it is currently occupied.");
                }
                if (adminService != null) {
                    adminService.reassignOrDeleteReservation(code);
                }
                if (!parkingService.deleteParkingSpace(code)) {
                    throw new IllegalStateException("Could not delete space \"" + code + "\".");
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    loadSpaces();
                } catch (InterruptedException | ExecutionException e) {
                    adminView.setLoading(false);
                    Throwable cause = e.getCause();
                    adminView.showError(cause != null ? cause.getMessage() : "Failed to delete space.");
                }
            }
        }.execute();
    }

    /**
     * Loads all parking spaces from the database and updates the view table.
     * Uses a generation counter to discard results from stale background tasks.
     */
    public void loadSpaces() {
        spacesLoadId++;
        int loadId = spacesLoadId;

        adminView.setLoading(true);

        new SwingWorker<Set<String>, ParkingSpace>() {
            @Override
            protected Set<String> doInBackground() {
                List<ParkingSpace> spaces = parkingService.getAllSpaces();
                Set<String> loadedCodes = new HashSet<>();

                for (ParkingSpace space : spaces) {
                    loadedCodes.add(space.getId());
                    delayRowLoad();
                    if (Thread.currentThread().isInterrupted()) {
                        break;
                    }
                    if (loadId == spacesLoadId) {
                        publish(space);
                    }
                }

                return loadedCodes;
            }

            @Override
            protected void process(List<ParkingSpace> chunks) {
                if (loadId != spacesLoadId)
                    return;

                for (ParkingSpace space : chunks) {
                    adminView.addSpaceToTable(space);
                }
            }

            @Override
            protected void done() {
                if (loadId != spacesLoadId)
                    return;

                try {
                    Set<String> loadedCodes = get();
                    adminView.removeSpacesNotIn(loadedCodes);
                    adminView.closeActiveDeleteDialogIfTargetUnavailable();
                    adminView.closeActiveEditDialogIfTargetUnavailable();
                } catch (InterruptedException | ExecutionException e) {
                    adminView.showError("Failed to load spaces: " + e.getMessage());
                } finally {
                    adminView.setLoading(false);
                }
            }
        }.execute();
    }

    private void delayRowLoad() {
        // Row-by-row display delay disabled because automatic refreshes should be fast.
        // try {
        // Thread.sleep(ROW_LOAD_DELAY_MS);
        // } catch (InterruptedException e) {
        // Thread.currentThread().interrupt();
        // }
    }
}
