package Presentation.Controllers;

import Business.Entities.ParkingSpace;
import Business.Entities.VehicleType;
import Business.Services.AdminService;
import Business.Services.DeleteParkingSpaceResult;
import Business.Services.ParkingService;
import Presentation.Views.AdminParkingActions;
import Presentation.Views.AdminParkingManagementView;

import javax.swing.SwingWorker;
import javax.swing.SwingUtilities;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ExecutionException;

/**
 * Controller for the admin parking space management view. Handles creating, editing, deleting, and loading
 * parking spaces.
 * <p>
 * The controller receives actions from the view, calls the needed service, and then asks the view to show
 * the result. This keeps Swing code separate from the business rules.
 * </p>
 */
public class AdminController implements AdminParkingActions {
    private AdminParkingManagementView adminView;
    private ParkingService parkingService;
    private AdminService adminService;
    private Runnable logoutAction;
    private Runnable parkingStatusDisplayAction;
    private volatile int spacesLoadId;

    /**
     * Constructs the controller and wires it to the given view.
     * <p>
     * The constructor receives the objects or values this class needs and stores them before the rest of
     * the methods are used.
     * </p>
     *
     * @param adminView the admin parking management view
     * @param parkingService the parking service
     */
    public AdminController(AdminParkingManagementView adminView, ParkingService parkingService) {
        this.adminView = adminView;
        this.parkingService = parkingService;
        setViewController();
        setViewLogoutListener();
    }

    /**
     * Sets the admin service used for reservation operations.
     * <p>
     * The setter keeps the field change inside this object instead of letting other classes touch the field
     * directly.
     * </p>
     *
     * @param adminService admin service used to apply the needed project logic
     */
    public void setAdminService(AdminService adminService) {
        this.adminService = adminService;
    }

    /**
     * Sets the action used when the admin logs out from this dialog.
     * <p>
     * The setter keeps the field change inside this object instead of letting other classes touch the field
     * directly.
     * </p>
     *
     * @param logoutAction logout action used by this operation
     */
    public void setLogoutAction(Runnable logoutAction) {
        this.logoutAction = logoutAction;
    }

    /**
     * Sets the action used to show the current parking status after creation.
     * <p>
     * The setter keeps the field change inside this object instead of letting other classes touch the field
     * directly.
     * </p>
     *
     * @param parkingStatusDisplayAction parking status display action used by this operation
     */
    public void setParkingStatusDisplayAction(Runnable parkingStatusDisplayAction) {
        this.parkingStatusDisplayAction = parkingStatusDisplayAction;
    }

    /**
     * Clears the table, loads all spaces, and makes the view visible.
     * <p>
     * This method prepares the information needed for a dialog and lets the view handle the actual Swing
     * display.
     * </p>
     */
    public void showView() {
        clearSpacesTable();
        loadSpaces();
        showAdminView();
    }

    /**
     * Reloads the view if it is currently visible. Safe to call from any thread.
     * <p>
     * This method asks the service for fresh data and sends it back to the visible table or dialog when the
     * screen needs to change.
     * </p>
     */
    public void refreshIfVisible() {
        if (!isAdminViewVisible())
            return;

        if (SwingUtilities.isEventDispatchThread()) {
            loadSpaces();
        } else {
            SwingUtilities.invokeLater(() -> loadSpaces());
        }
    }

    /**
     * Creates a new parking space on the given floor with the given vehicle type. The space code is
     * auto-generated by the service.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param floor the floor number
     * @param type the vehicle type for the space
     */
    public void createSpace(int floor, VehicleType type) {
        setLoading(true);
        new SwingWorker<ParkingSpace, Void>() {
            /**
             * Runs the worker task away from the Swing screen thread.
             * <p>
             * This runs away from the Swing screen thread so database work or longer calculations do not
             * freeze the interface while the user is waiting.
             * </p>
             *
             * @return the result of the operation
             * @throws Exception if the operation cannot be completed correctly
             */
            @Override
            protected ParkingSpace doInBackground() throws Exception {
                ParkingSpace space = new ParkingSpace(null, floor, type, false, false, null, null);
                createParkingSpace(space);
                return space;
            }

            /**
             * Refreshes the view after the create operation finishes.
             * <p>
             * This runs when the worker has finished, so it can read the final result, restore buttons or
             * cursors, and show the user a message if something failed.
             * </p>
             */
            @Override
            protected void done() {
                try {
                    ParkingSpace createdSpace = get();
                    showInfo("Parking space \"" + createdSpace.getId() + "\" was created successfully.");
                    loadSpaces();
                    showParkingStatusView();
                } catch (InterruptedException | ExecutionException e) {
                    setLoading(false);
                    Throwable cause = e.getCause();
                    showError(cause != null ? cause.getMessage() : "Failed to create space.");
                }
            }
        }.execute();
    }

    /**
     * Handles clear session state.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     */
    public void clearSessionState() {
        spacesLoadId++;
        clearAdminViewSessionState();
    }

    /**
     * Handles edit space.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param code the space code to edit
     * @param floor the new floor number
     * @param type the new vehicle type
     */
    public void editSpace(String code, int floor, VehicleType type) {
        setLoading(true);
        new SwingWorker<Void, Void>() {
            /**
             * Runs the worker task away from the Swing screen thread.
             * <p>
             * This runs away from the Swing screen thread so database work or longer calculations do not
             * freeze the interface while the user is waiting.
             * </p>
             *
             * @return the result of the operation
             * @throws Exception if the operation cannot be completed correctly
             */
            @Override
            protected Void doInBackground() throws Exception {
                ParkingSpace space = findParkingSpace(code);
                if (space == null) {
                    throw new IllegalArgumentException("Space not found: " + code);
                }
                space.setFloor(floor);
                space.setVehicleType(type);
                updateParkingSpaceDetails(space);
                return null;
            }

            /**
             * Refreshes the view after the edit operation finishes.
             * <p>
             * This runs when the worker has finished, so it can read the final result, restore buttons or
             * cursors, and show the user a message if something failed.
             * </p>
             */
            @Override
            protected void done() {
                try {
                    get();
                    loadSpaces();
                } catch (InterruptedException | ExecutionException e) {
                    setLoading(false);
                    Throwable cause = e.getCause();
                    showError(cause != null ? cause.getMessage() : "Failed to edit space.");
                }
            }
        }.execute();
    }

    /**
     * Deletes a parking space by code. Occupied spaces cannot be deleted. Any active reservation is
     * reassigned or cancelled by the admin service before deletion.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param code the space code to delete
     */
    public void deleteSpace(String code) {
        setLoading(true);
        new SwingWorker<DeleteParkingSpaceResult, Void>() {
            /**
             * Runs the worker task away from the Swing screen thread.
             * <p>
             * This runs away from the Swing screen thread so database work or longer calculations do not
             * freeze the interface while the user is waiting.
             * </p>
             *
             * @return the result of the operation
             * @throws Exception if the operation cannot be completed correctly
             */
            @Override
            protected DeleteParkingSpaceResult doInBackground() throws Exception {
                if (adminService == null) {
                    throw new IllegalStateException("Admin service is not available.");
                }
                return deleteParkingSpace(code);
            }

            /**
             * Refreshes the view after the delete operation finishes.
             * <p>
             * This runs when the worker has finished, so it can read the final result, restore buttons or
             * cursors, and show the user a message if something failed.
             * </p>
             */
            @Override
            protected void done() {
                try {
                    DeleteParkingSpaceResult result = get();
                    showInfo(buildDeleteSpaceMessage(result));
                    loadSpaces();
                    notifyParkingStatusChanged();
                } catch (InterruptedException | ExecutionException e) {
                    setLoading(false);
                    Throwable cause = e.getCause();
                    showError(cause != null ? cause.getMessage() : "Failed to delete space.");
                }
            }
        }.execute();
    }

    /**
     * Loads all parking spaces from the database and updates the view table.
     * <p>
     * This method asks the service for fresh data and sends it back to the visible table or dialog when the
     * screen needs to change.
     * </p>
     */
    public void loadSpaces() {
        spacesLoadId++;
        int loadId = spacesLoadId;

        setLoading(true);

        new SwingWorker<Set<String>, ParkingSpace>() {
            /**
             * Runs the worker task away from the Swing screen thread.
             * <p>
             * This runs away from the Swing screen thread so database work or longer calculations do not
             * freeze the interface while the user is waiting.
             * </p>
             *
             * @return the set of values found for the operation
             */
            @Override
            protected Set<String> doInBackground() {
                List<ParkingSpace> spaces = loadAllSpaces();
                Set<String> loadedCodes = new HashSet<>();

                for (ParkingSpace space : spaces) {
                    loadedCodes.add(space.getId());
                    if (Thread.currentThread().isInterrupted()) {
                        break;
                    }
                    if (loadId == spacesLoadId) {
                        publish(space);
                    }
                }

                return loadedCodes;
            }

            /**
             * Applies worker updates on the Swing screen thread.
             * <p>
             * This receives the values published by the worker on the Swing screen thread, which makes it
             * safe to add rows or refresh visible components little by little.
             * </p>
             *
             * @param chunks chunks used by this operation
             */
            @Override
            protected void process(List<ParkingSpace> chunks) {
                if (loadId != spacesLoadId)
                    return;

                for (ParkingSpace space : chunks) {
                    addSpaceToTable(space);
                }
            }

            /**
             * Finishes the worker task on the Swing screen thread.
             * <p>
             * This runs when the worker has finished, so it can read the final result, restore buttons or
             * cursors, and show the user a message if something failed.
             * </p>
             */
            @Override
            protected void done() {
                if (loadId != spacesLoadId)
                    return;

                try {
                    Set<String> loadedCodes = get();
                    removeSpacesNotIn(loadedCodes);
                    closeActiveDeleteDialogIfTargetUnavailable();
                    closeActiveEditDialogIfTargetUnavailable();
                } catch (InterruptedException | ExecutionException e) {
                    showError("Failed to load spaces: " + e.getMessage());
                } finally {
                    setLoading(false);
                }
            }
        }.execute();
    }

    /**
     * Sets this controller on the admin view.
     * <p>
     * The setter keeps the field change inside this object instead of letting other classes touch the field
     * directly.
     * </p>
     */
    private void setViewController() {
        adminView.setActions(this);
    }

    /**
     * Connects the dialog logout button to this controller.
     * <p>
     * The setter keeps the field change inside this object instead of letting other classes touch the field
     * directly.
     * </p>
     */
    private void setViewLogoutListener() {
        adminView.addLogoutListener(e -> logoutIfConfirmed());
    }

    /**
     * Handles clear spaces table.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     */
    private void clearSpacesTable() {
        adminView.clearSpacesTable();
    }

    /**
     * Makes the admin view visible.
     * <p>
     * This method prepares the information needed for a dialog and lets the view handle the actual Swing
     * display.
     * </p>
     */
    private void showAdminView() {
        adminView.setVisible(true);
    }

    /**
     * Clears user-related data from the admin management view.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     */
    private void clearAdminViewSessionState() {
        adminView.clearSessionViewState();
    }

    /**
     * Logs out from the admin dialog after confirmation.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     */
    private void logoutIfConfirmed() {
        if (logoutAction != null && adminView.confirmLogout()) {
            adminView.dispose();
            logoutAction.run();
        }
    }

    /**
     * Checks whether the admin view is visible.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @return true when the condition is met, false otherwise
     */
    private boolean isAdminViewVisible() {
        return adminView != null && adminView.isVisible();
    }

    /**
     * Sets the loading state on the admin view.
     * <p>
     * The setter keeps the field change inside this object instead of letting other classes touch the field
     * directly.
     * </p>
     *
     * @param loading true while the screen is waiting for an operation to finish
     */
    private void setLoading(boolean loading) {
        adminView.setLoading(loading);
    }

    /**
     * Shows an error in the admin view.
     * <p>
     * This method prepares the information needed for a dialog and lets the view handle the actual Swing
     * display.
     * </p>
     *
     * @param message message shown to the user or written to the log
     */
    private void showError(String message) {
        adminView.showError(message);
    }

    /**
     * Shows an information message in the admin view.
     * <p>
     * This method prepares the information needed for a dialog and lets the view handle the actual Swing
     * display.
     * </p>
     *
     * @param message message shown to the user or written to the log
     */
    private void showInfo(String message) {
        adminView.showInfo(message);
    }

    /**
     * Creates a parking space.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param space space used by this operation
     */
    private void createParkingSpace(ParkingSpace space) {
        parkingService.createParkingSpace(space);
    }

    /**
     * Finds parking space.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param code parking space code involved in the operation
     * @return the matching parking space, or null when it is not found
     */
    private ParkingSpace findParkingSpace(String code) {
        return parkingService.findByCode(code);
    }

    /**
     * Updates parking space details.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param space space used by this operation
     */
    private void updateParkingSpaceDetails(ParkingSpace space) {
        parkingService.updateParkingSpaceDetails(space);
    }

    /**
     * Deletes a parking space.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param code parking space code involved in the operation
     * @return the result of the operation
     */
    private DeleteParkingSpaceResult deleteParkingSpace(String code) {
        return adminService.deleteParkingSpace(code);
    }

    /**
     * Loads all spaces.
     * <p>
     * This method asks the service for fresh data and sends it back to the visible table or dialog when the
     * screen needs to change.
     * </p>
     *
     * @return the loaded all spaces
     */
    private List<ParkingSpace> loadAllSpaces() {
        return parkingService.getAllSpaces();
    }

    /**
     * Adds a parking space row to the view.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param space space used by this operation
     */
    private void addSpaceToTable(ParkingSpace space) {
        adminView.addSpaceToTable(space);
    }

    /**
     * Handles remove spaces not in.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param loadedCodes loaded codes used by this operation
     */
    private void removeSpacesNotIn(Set<String> loadedCodes) {
        adminView.removeSpacesNotIn(loadedCodes);
    }

    /**
     * Closes delete dialogs that are no longer valid.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     */
    private void closeActiveDeleteDialogIfTargetUnavailable() {
        adminView.closeActiveDeleteDialogIfTargetUnavailable();
    }

    /**
     * Closes edit dialogs that are no longer valid.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     */
    private void closeActiveEditDialogIfTargetUnavailable() {
        adminView.closeActiveEditDialogIfTargetUnavailable();
    }

    /**
     * Shows the parking status view after a space is created.
     * <p>
     * This method prepares the information needed for a dialog and lets the view handle the actual Swing
     * display.
     * </p>
     */
    private void showParkingStatusView() {
        if (parkingStatusDisplayAction != null) {
            parkingStatusDisplayAction.run();
        }
    }

    /**
     * Refreshes related parking screens after a space deletion.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     */
    private void notifyParkingStatusChanged() {
        if (parkingStatusDisplayAction != null) {
            parkingStatusDisplayAction.run();
        }
    }

    /**
     * Builds delete space message.
     * <p>
     * This method keeps the controller action separate from the view code and from the business rule
     * itself.
     * </p>
     *
     * @param result result used by this operation
     * @return the built delete space message
     */
    private String buildDeleteSpaceMessage(DeleteParkingSpaceResult result) {
        String message = "Parking space \"" + result.getDeletedSpaceCode() + "\" was deleted.";

        if (!result.hasAffectedReservation()) {
            return message;
        }

        if (result.isReservationCancelled()) {
            return message + "\nReservation for plate \"" + result.getAffectedPlate()
                    + "\" was cancelled because no similar vacant space was available.";
        }

        return message + "\nReservation for plate \"" + result.getAffectedPlate()
                + "\" was moved to space \"" + result.getNewSpaceCode() + "\".";
    }

}
