package Presentation.Controllers;

import Business.Entities.ParkingSpace;
import Business.Entities.VehicleType;
import Business.Services.AdminService;
import Business.Services.DeleteParkingSpaceResult;
import Business.Services.ParkingService;
import Presentation.Views.AdminParkingActions;
import Presentation.Views.AdminParkingManagementView;

import javax.swing.SwingWorker;
import javax.swing.SwingUtilities;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ExecutionException;

/**
 * Controller for the admin parking space management view.
 * Handles creating, editing, deleting, and loading parking spaces.
 */
public class AdminController implements AdminParkingActions {
    private AdminParkingManagementView adminView;
    private ParkingService parkingService;
    private AdminService adminService;
    private Runnable logoutAction;
    private Runnable parkingStatusDisplayAction;
    private volatile int spacesLoadId;

    /**
     * Constructs the controller and wires it to the given view.
     *
     * @param adminView      the admin parking management view
     * @param parkingService the parking service
     */
    public AdminController(AdminParkingManagementView adminView, ParkingService parkingService) {
        this.adminView = adminView;
        this.parkingService = parkingService;
        setViewController();
        setViewLogoutListener();
    }

    /** Sets the admin service used for reservation operations. */
    public void setAdminService(AdminService adminService) {
        this.adminService = adminService;
    }

    /** Sets the action used when the admin logs out from this dialog. */
    public void setLogoutAction(Runnable logoutAction) {
        this.logoutAction = logoutAction;
    }

    /** Sets the action used to show the current parking status after creation. */
    public void setParkingStatusDisplayAction(Runnable parkingStatusDisplayAction) {
        this.parkingStatusDisplayAction = parkingStatusDisplayAction;
    }

    /** Clears the table, loads all spaces, and makes the view visible. */
    public void showView() {
        clearSpacesTable();
        loadSpaces();
        showAdminView();
    }

    /**
     * Reloads the view if it is currently visible.
     * Safe to call from any thread.
     */
    public void refreshIfVisible() {
        if (!isAdminViewVisible())
            return;

        if (SwingUtilities.isEventDispatchThread()) {
            loadSpaces();
        } else {
            SwingUtilities.invokeLater(() -> loadSpaces());
        }
    }

    /**
     * Creates a new parking space on the given floor with the given vehicle type.
     * The space code is auto-generated by the service.
     *
     * @param floor the floor number
     * @param type  the vehicle type for the space
     */
    public void createSpace(int floor, VehicleType type) {
        setLoading(true);
        new SwingWorker<ParkingSpace, Void>() {
            /** Creates the space away from the EDT. */
            @Override
            protected ParkingSpace doInBackground() throws Exception {
                ParkingSpace space = new ParkingSpace(null, floor, type, false, false, null, null);
                createParkingSpace(space);
                return space;
            }

            /** Refreshes the view after the create operation finishes. */
            @Override
            protected void done() {
                try {
                    ParkingSpace createdSpace = get();
                    showInfo("Parking space \"" + createdSpace.getId() + "\" was created successfully.");
                    loadSpaces();
                    showParkingStatusView();
                } catch (InterruptedException | ExecutionException e) {
                    setLoading(false);
                    Throwable cause = e.getCause();
                    showError(cause != null ? cause.getMessage() : "Failed to create space.");
                }
            }
        }.execute();
    }

    /** Clears admin management state when the active user session ends. */
    public void clearSessionState() {
        spacesLoadId++;
        clearAdminViewSessionState();
    }

    /**
     * Updates the floor and vehicle type of an existing parking space.
     *
     * @param code  the space code to edit
     * @param floor the new floor number
     * @param type  the new vehicle type
     */
    public void editSpace(String code, int floor, VehicleType type) {
        setLoading(true);
        new SwingWorker<Void, Void>() {
            /** Saves the edited space away from the EDT. */
            @Override
            protected Void doInBackground() throws Exception {
                ParkingSpace space = findParkingSpace(code);
                if (space == null) {
                    throw new IllegalArgumentException("Space not found: " + code);
                }
                space.setFloor(floor);
                space.setVehicleType(type);
                updateParkingSpaceDetails(space);
                return null;
            }

            /** Refreshes the view after the edit operation finishes. */
            @Override
            protected void done() {
                try {
                    get();
                    loadSpaces();
                } catch (InterruptedException | ExecutionException e) {
                    setLoading(false);
                    Throwable cause = e.getCause();
                    showError(cause != null ? cause.getMessage() : "Failed to edit space.");
                }
            }
        }.execute();
    }

    /**
     * Deletes a parking space by code.
     * Occupied spaces cannot be deleted.
     * Any active reservation is reassigned or cancelled by the admin service
     * before deletion.
     *
     * @param code the space code to delete
     */
    public void deleteSpace(String code) {
        setLoading(true);
        new SwingWorker<DeleteParkingSpaceResult, Void>() {
            /** Deletes the space away from the EDT. */
            @Override
            protected DeleteParkingSpaceResult doInBackground() throws Exception {
                if (adminService == null) {
                    throw new IllegalStateException("Admin service is not available.");
                }
                return deleteParkingSpace(code);
            }

            /** Refreshes the view after the delete operation finishes. */
            @Override
            protected void done() {
                try {
                    DeleteParkingSpaceResult result = get();
                    showInfo(buildDeleteSpaceMessage(result));
                    loadSpaces();
                    notifyParkingStatusChanged();
                } catch (InterruptedException | ExecutionException e) {
                    setLoading(false);
                    Throwable cause = e.getCause();
                    showError(cause != null ? cause.getMessage() : "Failed to delete space.");
                }
            }
        }.execute();
    }

    /**
     * Loads all parking spaces from the database and updates the view table.
     * Uses a generation counter to discard results from stale background tasks.
     */
    public void loadSpaces() {
        spacesLoadId++;
        int loadId = spacesLoadId;

        setLoading(true);

        new SwingWorker<Set<String>, ParkingSpace>() {
            /** Loads spaces away from the EDT. */
            @Override
            protected Set<String> doInBackground() {
                List<ParkingSpace> spaces = loadAllSpaces();
                Set<String> loadedCodes = new HashSet<>();

                for (ParkingSpace space : spaces) {
                    loadedCodes.add(space.getId());
                    if (Thread.currentThread().isInterrupted()) {
                        break;
                    }
                    if (loadId == spacesLoadId) {
                        publish(space);
                    }
                }

                return loadedCodes;
            }

            /** Adds loaded rows to the table on the EDT. */
            @Override
            protected void process(List<ParkingSpace> chunks) {
                if (loadId != spacesLoadId)
                    return;

                for (ParkingSpace space : chunks) {
                    addSpaceToTable(space);
                }
            }

            /** Finishes the table refresh after loading spaces. */
            @Override
            protected void done() {
                if (loadId != spacesLoadId)
                    return;

                try {
                    Set<String> loadedCodes = get();
                    removeSpacesNotIn(loadedCodes);
                    closeActiveDeleteDialogIfTargetUnavailable();
                    closeActiveEditDialogIfTargetUnavailable();
                } catch (InterruptedException | ExecutionException e) {
                    showError("Failed to load spaces: " + e.getMessage());
                } finally {
                    setLoading(false);
                }
            }
        }.execute();
    }

    /** Sets this controller on the admin view. */
    private void setViewController() {
        adminView.setActions(this);
    }

    /** Connects the dialog logout button to this controller. */
    private void setViewLogoutListener() {
        adminView.addLogoutListener(e -> logoutIfConfirmed());
    }

    /** Clears the parking-space table. */
    private void clearSpacesTable() {
        adminView.clearSpacesTable();
    }

    /** Makes the admin view visible. */
    private void showAdminView() {
        adminView.setVisible(true);
    }

    /** Clears user-related data from the admin management view. */
    private void clearAdminViewSessionState() {
        adminView.clearSessionViewState();
    }

    /** Logs out from the admin dialog after confirmation. */
    private void logoutIfConfirmed() {
        if (logoutAction != null && adminView.confirmLogout()) {
            adminView.dispose();
            logoutAction.run();
        }
    }

    /** Checks whether the admin view is visible. */
    private boolean isAdminViewVisible() {
        return adminView != null && adminView.isVisible();
    }

    /** Sets the loading state on the admin view. */
    private void setLoading(boolean loading) {
        adminView.setLoading(loading);
    }

    /** Shows an error in the admin view. */
    private void showError(String message) {
        adminView.showError(message);
    }

    /** Shows an information message in the admin view. */
    private void showInfo(String message) {
        adminView.showInfo(message);
    }

    /** Creates a parking space through the parking service. */
    private void createParkingSpace(ParkingSpace space) {
        parkingService.createParkingSpace(space);
    }

    /** Finds a parking space through the parking service. */
    private ParkingSpace findParkingSpace(String code) {
        return parkingService.findByCode(code);
    }

    /** Updates parking space details through the parking service. */
    private void updateParkingSpaceDetails(ParkingSpace space) {
        parkingService.updateParkingSpaceDetails(space);
    }

    /** Deletes a parking space through the admin service. */
    private DeleteParkingSpaceResult deleteParkingSpace(String code) {
        return adminService.deleteParkingSpace(code);
    }

    /** Loads all parking spaces through the parking service. */
    private List<ParkingSpace> loadAllSpaces() {
        return parkingService.getAllSpaces();
    }

    /** Adds a parking space row to the view. */
    private void addSpaceToTable(ParkingSpace space) {
        adminView.addSpaceToTable(space);
    }

    /** Removes rows that are no longer present. */
    private void removeSpacesNotIn(Set<String> loadedCodes) {
        adminView.removeSpacesNotIn(loadedCodes);
    }

    /** Closes delete dialogs that are no longer valid. */
    private void closeActiveDeleteDialogIfTargetUnavailable() {
        adminView.closeActiveDeleteDialogIfTargetUnavailable();
    }

    /** Closes edit dialogs that are no longer valid. */
    private void closeActiveEditDialogIfTargetUnavailable() {
        adminView.closeActiveEditDialogIfTargetUnavailable();
    }

    /** Shows the parking status view after a space is created. */
    private void showParkingStatusView() {
        if (parkingStatusDisplayAction != null) {
            parkingStatusDisplayAction.run();
        }
    }

    /** Refreshes related parking screens after a space deletion. */
    private void notifyParkingStatusChanged() {
        if (parkingStatusDisplayAction != null) {
            parkingStatusDisplayAction.run();
        }
    }

    /** Builds the admin message shown after deleting a parking space. */
    private String buildDeleteSpaceMessage(DeleteParkingSpaceResult result) {
        String message = "Parking space \"" + result.getDeletedSpaceCode() + "\" was deleted.";

        if (!result.hasAffectedReservation()) {
            return message;
        }

        if (result.isReservationCancelled()) {
            return message + "\nReservation for plate \"" + result.getAffectedPlate()
                    + "\" was cancelled because no similar vacant space was available.";
        }

        return message + "\nReservation for plate \"" + result.getAffectedPlate()
                + "\" was moved to space \"" + result.getNewSpaceCode() + "\".";
    }

}
